python run_class_finetuning.py ^
    --model vit_small_patch16_224 ^
    --data_set Kinetics-400 --nb_classes 10 ^
    --data_path E:\Job\ASUS\AICUP\Public\train_test ^
    --data_root E:\Job\ASUS\AICUP\Public\train_test ^
    --finetune ./OUTPUT/mvd_vit_small_with_vit_base_teacher_k400_epoch_400/20230503/checkpoint-19.pth ^
    --log_dir ./OUTPUT/mvd_vit_small_with_vit_base_teacher_k400_epoch_400/20230503/finetune_on_custom ^
    --output_dir ./OUTPUT/mvd_vit_small_with_vit_base_teacher_k400_epoch_400/20230504/finetune_on_custom ^
    --input_size 224 --short_side_size 224 ^
    --opt adamw --opt_betas 0.9 0.999 --weight_decay 0.05 ^
    --batch_size 1 --update_freq 2 --num_sample 2 ^
    --save_ckpt_freq 5 ^
    --num_frames 16 --sampling_rate 4 ^
    --lr 5e-4 --epochs 150 ^
    --dist_eval --test_num_segment 5 --test_num_crop 3
